In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#LOADING THE DATA
weather_forecast_df = pd.read_csv("../raw_data/weather_forecast_2018_2023.csv")

In [3]:
#DROPPING UNNECESSARY COLUMNS
forecast_cleaned_df = weather_forecast_df.drop(columns=["convective","slice dt unixtime","lat","lon","dew_point","snow_depth","snow","pressure","ground_pressure","ice","fr_rain"])

In [4]:
#FORMATTING THE DATE COLUMNS
forecast_cleaned_df['forecast dt iso'] = forecast_cleaned_df['forecast dt iso'].str[:19]
forecast_cleaned_df['slice dt iso'] = forecast_cleaned_df['slice dt iso'].str[:19]
forecast_cleaned_df["forecast dt iso"] = pd.to_datetime(forecast_cleaned_df["forecast dt iso"],utc=True)
forecast_cleaned_df["slice dt iso"] = pd.to_datetime(forecast_cleaned_df["slice dt iso"],utc=True)

In [5]:
#ROUNDING THE FLOATS AND TURNING THEM TO INTEGERS
forecast_cleaned_df["clouds"] = forecast_cleaned_df["clouds"].round().astype(int)
forecast_cleaned_df["humidity"] = forecast_cleaned_df["humidity"].round().astype(int)
forecast_cleaned_df["wind_deg"] = forecast_cleaned_df["wind_deg"].round().astype(int)

In [6]:
#SPLITTING THE DATASET BASED ON THE PREDICTION STEPS
df_midnight_predictions = forecast_cleaned_df[forecast_cleaned_df["forecast dt iso"].dt.time == pd.Timestamp("00:00:00+00:00").time()]
df_midnight_predictions

,forecast dt unixtime,forecast dt iso,slice dt iso,temperature,humidity,clouds,wind_speed,wind_deg,rain,accumulated,hours,rate,probability
0,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 00:00:00+00:00,9.07,92,0,3.78,278,0.0,0.0,1.0,0.000000,0.00
1,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 01:00:00+00:00,9.49,89,33,4.64,281,0.0,0.0,1.0,0.000000,0.05
2,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 02:00:00+00:00,9.64,88,54,5.09,280,0.0,0.0,1.0,0.000000,0.04
3,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 03:00:00+00:00,9.63,89,64,5.25,276,0.0,0.0,1.0,0.000000,0.00
4,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 04:00:00+00:00,9.61,90,68,5.26,272,0.0,0.0,1.0,0.000008,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2618504,1672444800,2022-12-31 00:00:00+00:00,2023-01-15 20:00:00+00:00,1.92,76,45,4.96,271,0.0,0.0,1.0,0.000000,0.00
2618505,1672444800,2022-12-31 00:00:00+00:00,2023-01-15 21:00:00+00:00,1.57,77,19,5.20,269,0.0,0.0,1.0,0.000000,0.00
2618506,1672444800,2022-12-31 00:00:00+00:00,2023-01-15 22:00:00+00:00,1.30,77,0,5.45,268,0.0,0.0,1.0,0.000000,0.00
2618507,1672444800,2022-12-31 00:00:00+00:00,2023-01-15 23:00:00+00:00,1.12,76,0,5.68,269,0.0,0.0,1.0,0.000000,0.00
2618508,1672444800,2022-12-31 00:00:00+00:00,2023-01-16 00:00:00+00:00,1.05,74,13,5.86,271,0.0,0.0,1.0,0.000000,0.00

In [7]:
# 1-Filter the rows between 8 am and 10 pm
df_midnight_predictions['slice dt iso'] = pd.to_datetime(df_midnight_predictions['slice dt iso'], format='%Y-%m-%d %H:%M:%S')
df_filtered = df_midnight_predictions[(df_midnight_predictions['slice dt iso'].dt.hour >= 8) & (df_midnight_predictions['slice dt iso'].dt.hour <= 22)]
df_filtered.head(17)

/tmp/ipykernel_59600/2099684625.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_midnight_predictions['slice dt iso'] = pd.to_datetime(df_midnight_predictions['slice dt iso'], format='%Y-%m-%d %H:%M:%S')

,forecast dt unixtime,forecast dt iso,slice dt iso,temperature,humidity,clouds,wind_speed,wind_deg,rain,accumulated,hours,rate,probability
8,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 08:00:00+00:00,11.52,75,82,5.95,266,0.13,0.13,1.0,0.000036,0.24
9,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 09:00:00+00:00,12.22,69,88,6.35,266,0.12,0.12,1.0,0.000033,0.30
10,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 10:00:00+00:00,12.63,65,91,6.67,263,0.11,0.11,1.0,0.000031,0.26
11,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 11:00:00+00:00,12.78,64,93,6.88,257,0.00,0.00,1.0,0.000025,0.19
12,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 12:00:00+00:00,12.74,63,94,6.95,250,0.00,0.00,1.0,0.000022,0.21
13,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 13:00:00+00:00,12.58,64,96,6.88,242,0.00,0.00,1.0,0.000025,0.40
14,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 14:00:00+00:00,12.29,65,98,6.80,235,0.12,0.12,1.0,0.000033,0.67
15,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 15:00:00+00:00,11.84,67,100,6.87,230,0.19,0.19,1.0,0.000053,0.90
16,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 16:00:00+00:00,11.23,71,100,7.20,228,0.29,0.29,1.0,0.000081,1.00
17,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 17:00:00+00:00,10.66,76,100,7.63,227,0.40,0.40,1.0,0.000111,1.00
18,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 18:00:00+00:00,10.32,80,100,7.93,229,0.48,0.48,1.0,0.000133,1.00
19,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 19:00:00+00:00,10.37,82,99,7.95,232,0.52,0.52,1.0,0.000144,0.98
20,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 20:00:00+00:00,10.68,83,99,7.75,237,0.54,0.54,1.0,0.000150,0.97
21,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 21:00:00+00:00,11.08,84,100,7.44,243,0.60,0.60,1.0,0.000167,1.00
22,1507334400,2017-10-07 00:00:00+00:00,2017-10-07 22:00:00+00:00,11.41,85,100,7.13,251,0.73,0.73,1.0,0.000203,1.00
32,1507334400,2017-10-07 00:00:00+00:00,2017-10-08 08:00:00+00:00,12.22,72,65,5.31,319,0.13,0.13,1.0,0.000036,0.57
33,1507334400,2017-10-07 00:00:00+00:00,2017-10-08 09:00:00+00:00,12.63,64,50,4.91,323,0.00,0.00,1.0,0.000017,0.49

In [81]:
# 2-creat mean_rain*probability
df_filtered['rain*probability'] = df_filtered['rain'] * df_filtered['probability']
#set the index 
df_filtered.reset_index(drop=True, inplace=True)
#remove the hours in the date
df_filtered['slice dt iso'] = pd.to_datetime(df_filtered['slice dt iso'], format='%Y-%m-%d').dt.date
df_filtered['forecast dt iso'] = pd.to_datetime(df_filtered['forecast dt iso'], format='%Y-%m-%d').dt.date
#from object to date
df_filtered['slice dt iso'] = pd.to_datetime(df_filtered['slice dt iso'])
df_filtered['forecast dt iso'] = pd.to_datetime(df_filtered['forecast dt iso'])
df_filtered.head(200)

/tmp/ipykernel_59600/296036650.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['rain*probability'] = df_filtered['rain'] * df_filtered['probability']
/tmp/ipykernel_59600/296036650.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['slice dt iso'] = pd.to_datetime(df_filtered['slice dt iso'], format='%Y-%m-%d').dt.date
/tmp/ipykernel_59600/296036650.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['forecast dt iso'] = pd.to_datetime(df_filtered['forecast dt iso'], format='%Y-%m-%d').dt.date
/tmp/ipykernel_59600/296036650.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['slice dt iso'] = pd.to_datetime(df_filtered['slice dt iso'])
/tmp/ipykernel_59600/296036650.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['forecast dt iso'] = pd.to_datetime(df_filtered['forecast dt iso'])

,forecast dt unixtime,forecast dt iso,slice dt iso,temperature,humidity,clouds,wind_speed,wind_deg,rain,accumulated,hours,rate,probability,rain*probability
0,1507334400,2017-10-07,2017-10-07,11.52,75,82,5.95,266,0.13,0.13,1.0,0.000036,0.24,0.0312
1,1507334400,2017-10-07,2017-10-07,12.22,69,88,6.35,266,0.12,0.12,1.0,0.000033,0.30,0.0360
2,1507334400,2017-10-07,2017-10-07,12.63,65,91,6.67,263,0.11,0.11,1.0,0.000031,0.26,0.0286
3,1507334400,2017-10-07,2017-10-07,12.78,64,93,6.88,257,0.00,0.00,1.0,0.000025,0.19,0.0000
4,1507334400,2017-10-07,2017-10-07,12.74,63,94,6.95,250,0.00,0.00,1.0,0.000022,0.21,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1507420800,2017-10-08,2017-10-10,13.69,78,100,5.56,242,0.37,0.37,1.0,0.000103,1.00,0.3700
196,1507420800,2017-10-08,2017-10-10,13.55,80,100,6.32,247,0.42,0.42,1.0,0.000117,1.00,0.4200
197,1507420800,2017-10-08,2017-10-10,13.53,83,100,6.54,253,0.42,0.42,1.0,0.000117,0.91,0.3822
198,1507420800,2017-10-08,2017-10-10,13.57,85,100,6.34,258,0.39,0.39,1.0,0.000108,0.80,0.3120
199,1507420800,2017-10-08,2017-10-10,13.60,87,100,5.98,261,0.33,0.33,1.0,0.000092,0.74,0.2442

In [83]:
df_final = df_filtered.groupby(df_filtered['slice dt iso'].dt.date).agg({'forecast dt iso': 'first','slice dt iso': 'first',
                                                           'temperature': 'mean', 'humidity': 'mean', 
                                                            'clouds': 'mean', 'wind_speed': 'mean',
                                                            'wind_deg': 'mean', 'accumulated': 'mean',
                                                            'rain*probability': 'sum'})

df_final = df_final.reset_index(drop=True)
df_final.tail(50)

,forecast dt iso,slice dt iso,temperature,humidity,clouds,wind_speed,wind_deg,accumulated,rain*probability
1877,2022-11-12,2022-11-27,5.555625,80.866667,78.262500,3.075958,151.941667,0.008000,1.1152
1878,2022-11-13,2022-11-28,5.065792,80.291667,83.925000,3.793458,159.541667,0.034167,7.0600
1879,2022-11-14,2022-11-29,4.685542,81.445833,88.700000,2.899750,154.145833,0.057375,7.5730
1880,2022-11-15,2022-11-30,4.522667,77.454167,83.604167,3.146625,127.212500,0.019333,2.6731
1881,2022-11-16,2022-12-01,3.176417,77.729167,70.850000,3.357083,117.987500,0.004625,0.4965
1882,2022-11-17,2022-12-02,2.064708,75.529167,70.250000,3.161750,116.875000,0.004708,0.7462
1883,2022-11-18,2022-12-03,1.599500,79.066667,82.954167,3.040583,121.470833,0.019333,1.8344
1884,2022-11-19,2022-12-04,1.670167,85.212500,76.491667,2.772708,97.941667,0.010000,0.0685
1885,2022-11-20,2022-12-05,1.913833,87.362500,84.037500,2.831167,155.366667,0.045083,2.3808
1886,2022-11-21,2022-12-06,1.554375,85.095833,78.787500,3.296667,173.354167,0.078708,5.5862
1887,2022-11-22,2022-12-07,1.462958,81.408333,81.258333,3.965833,184.200000,0.053750,5.4389
1888,2022-11-23,2022-12-08,0.899667,84.791667,80.366667,2.803208,188.683333,0.078458,10.8475
1889,2022-11-24,2022-12-09,-0.026167,80.816667,63.208333,2.348833,125.537500,0.053250,10.8928
1890,2022-11-25,2022-12-10,-0.404000,85.154167,59.420833,2.238875,146.379167,0.056083,10.5878
1891,2022-11-26,2022-12-11,-0.373833,83.420833,83.450000,3.032250,133.266667,0.011625,0.7068
1892,2022-11-27,2022-12-12,-0.535625,85.483333,85.437500,3.881000,204.695833,0.112833,1.2670
1893,2022-11-28,2022-12-13,-1.803750,85.800000,65.366667,2.902083,232.591667,0.032625,1.9653
1894,2022-11-29,2022-12-14,-2.285750,83.562500,80.195833,3.230250,153.175000,0.015125,1.0410
1895,2022-11-30,2022-12-15,-3.205000,83.666667,52.995833,3.269958,200.920833,0.040833,1.8080
1896,2022-12-01,2022-12-16,-3.047917,84.700000,57.091667,2.826083,177.841667,0.050750,0.0000
1897,2022-12-02,2022-12-17,-2.699958,89.404167,63.991667,2.210333,175.166667,0.025167,1.7400
1898,2022-12-03,2022-12-18,-3.136375,83.904167,63.008333,3.489208,174.387500,0.031167,2.8792
1899,2022-12-04,2022-12-19,0.456500,85.141667,94.425000,4.835792,181.245833,0.172799,29.0550
1900,2022-12-05,2022-12-20,2.588542,88.345833,86.037500,4.598333,200.600000,0.087792,10.3395
1901,2022-12-06,2022-12-21,3.214250,87.062500,73.291667,4.408083,215.875000,0.051642,5.9467
1902,2022-12-07,2022-12-22,3.309292,87.208333,84.850000,4.717333,216.920833,0.117500,21.7482
1903,2022-12-08,2022-12-23,3.791208,89.975000,92.025000,3.642833,203.612500,0.216167,42.9867
1904,2022-12-09,2022-12-24,5.417833,83.820833,87.533333,4.678792,228.645833,0.076958,13.2816
1905,2022-12-10,2022-12-25,4.449375,83.987500,87.595833,4.030375,206.341667,0.076500,8.5953
1906,2022-12-11,2022-12-26,4.023917,80.020833,83.479167,4.477708,207.187500,0.142125,23.2664
1907,2022-12-12,2022-12-27,3.424000,76.958333,69.633333,4.830750,214.487500,0.010375,0.9092
1908,2022-12-13,2022-12-28,3.410500,77.008333,75.904167,4.684375,220.650000,0.038500,7.0158
1909,2022-12-14,2022-12-29,5.518042,75.733333,77.200000,4.711250,217.050000,0.021167,3.8085
1910,2022-12-15,2022-12-30,5.033000,76.300000,75.670833,4.965042,197.475000,0.042750,5.6832
1911,2022-12-16,2022-12-31,8.158208,75.141667,88.245833,5.850458,221.645833,0.042375,6.5333
1912,2022-12-17,2023-01-01,7.210133,76.351111,82.351111,4.264667,209.404444,0.053867,11.0488
1913,2022-12-18,2023-01-02,7.125143,74.171429,74.633333,4.382286,219.971429,0.052571,10.1389
1914,2022-12-19,2023-01-03,5.473333,77.605128,87.343590,3.943897,217.394872,0.145897,23.1008
1915,2022-12-20,2023-01-04,5.409389,81.166667,82.016667,4.251556,215.705556,0.190444,32.2854
1916,2022-12-21,2023-01-05,5.495697,79.890909,74.781818,4.168727,210.236364,0.124606,16.6992
1917,2022-12-22,2023-01-06,5.489067,76.073333,73.473333,5.253733,203.266667,0.096600,6.6947
1918,2022-12-23,2023-01-07,3.995407,68.051852,66.111111,4.463407,197.266667,0.009333,0.7182
1919,2022-12-24,2023-01-08,4.208917,66.816667,74.175000,5.361333,195.558333,0.055083,4.8925
1920,2022-12-25,2023-01-09,4.105905,72.019048,56.038095,4.611524,219.133333,0.077810,2.4885
1921,2022-12-26,2023-01-10,3.078222,73.400000,77.600000,4.406667,242.044444,0.045444,2.9906
1922,2022-12-27,2023-01-11,3.791733,76.440000,72.266667,4.139333,230.240000,0.113600,7.2749
1923,2022-12-28,2023-01-12,2.214000,77.500000,87.816667,4.229000,209.266667,0.027667,1.2619
1924,2022-12-29,2023-01-13,0.819556,76.644444,66.577778,4.454000,157.666667,0.042000,0.0000
1925,2022-12-30,2023-01-14,0.786333,72.966667,83.166667,2.628000,171.933333,0.000000,0.0000
1926,2022-12-31,2023-01-15,3.156000,78.000000,75.800000,4.756000,263.533333,0.000000,0.0000

In [82]:
#day by day working
import numpy as np

df_filtered[df_filtered["forecast dt iso"]== '2017-10-07'].groupby(df_filtered['slice dt iso'].dt.date).agg({'forecast dt iso': 'first','slice dt iso': 'first',
                                                           'temperature': 'mean', 'humidity': 'mean', 
                                                            'clouds': 'mean', 'wind_speed': 'mean',
                                                            'wind_deg': 'mean', 'accumulated': 'mean',
                                                            'rain*probability': 'sum'})

,forecast dt iso,slice dt iso,temperature,humidity,clouds,wind_speed,wind_deg,accumulated,rain*probability
slice dt iso,,,,,,,,,
2017-10-07,2017-10-07,2017-10-07,11.623333,72.866667,96.000000,7.092000,243.733333,0.282000,3.8806
2017-10-08,2017-10-07,2017-10-08,12.103333,58.000000,24.133333,4.310667,313.866667,0.008667,0.0741
2017-10-09,2017-10-07,2017-10-09,11.486667,64.400000,44.066667,3.703333,271.000000,0.000000,0.0000
2017-10-10,2017-10-07,2017-10-10,13.195333,78.066667,98.533333,6.192667,242.466667,0.502667,7.0928
2017-10-11,2017-10-07,2017-10-11,11.415333,77.133333,92.066667,6.812667,294.800000,0.237333,2.5650
2017-10-12,2017-10-07,2017-10-12,12.585333,82.666667,93.866667,4.808000,250.933333,0.043333,0.2476
2017-10-13,2017-10-07,2017-10-13,14.324667,78.400000,73.933333,3.118667,266.533333,0.000000,0.0000
2017-10-14,2017-10-07,2017-10-14,14.774000,84.466667,48.533333,1.928667,290.466667,0.000000,0.0000
2017-10-15,2017-10-07,2017-10-15,15.944000,73.200000,0.000000,2.134667,113.933333,0.000000,0.0000
2017-10-16,2017-10-07,2017-10-16,14.585333,63.200000,0.266667,4.928000,117.933333,0.000000,0.0000
2017-10-17,2017-10-07,2017-10-17,14.840000,56.000000,22.000000,4.505000,123.000000,0.000000,0.0000
2017-10-18,2017-10-07,2017-10-18,13.080000,53.000000,3.000000,2.400000,143.000000,0.000000,0.0000
2017-10-19,2017-10-07,2017-10-19,12.590000,61.000000,39.000000,1.564000,252.000000,0.000000,0.0000
2017-10-20,2017-10-07,2017-10-20,15.070000,64.000000,86.000000,3.879000,139.000000,0.000000,0.0000
2017-10-21,2017-10-07,2017-10-21,15.530000,63.000000,1.000000,4.145000,137.000000,0.000000,0.0000
2017-10-22,2017-10-07,2017-10-22,16.030000,69.000000,67.000000,3.816000,231.000000,0.125000,0.0000

In [93]:
#Extracting the list of dates to make a bolean masks for each 

dates_elements = df_filtered["forecast dt iso"].unique()

numpy.datetime64('2017-10-07T00:00:00.000000000')

In [115]:
# For loop to create a list of dataframes we want concatenate
# i is date 

df_list = []

for i in dates_elements:
    date_df = df_filtered[df_filtered["forecast dt iso"]== i].groupby(df_filtered['slice dt iso'].dt.date).agg({'forecast dt iso': 'first','slice dt iso': 'first',
                                                           'temperature': 'mean', 'humidity': 'mean', 
                                                            'clouds': 'mean', 'wind_speed': 'mean',
                                                            'wind_deg': 'mean', 'accumulated': 'mean',
                                                            'rain*probability': 'sum'})
    df_list.append(date_df)

In [133]:
#Creating the final dataframe aftere droping accumulated col and resetting the index
final_df = pd.concat(df_list, axis=0)
del final_df['accumulated']
final_df.reset_index(drop=True, inplace=True)
#rename colm
final_df = final_df.rename(columns={'slice dt iso': 'ds','temperature': 'temp','rain*probability':'rain'})
#set the decimals 
final_df['temp'] = final_df['temp'].round(2)
final_df['humidity'] = final_df['humidity'].round(0)
final_df['clouds'] = final_df['clouds'].round(0)
final_df['wind_speed'] = final_df['wind_speed'].round(2)
final_df['wind_deg'] = final_df['wind_deg'].round(0)
final_df['rain'] = final_df['rain'].round(2)

#save it as csv
final_df.to_csv('finall_pred_weather.csv', index=False)